Repository m3ntorship/pickly-playground, pull requests merged in 2021-01, with the labels that each got.

#11 Feature/poll tabs
  src/css/app.css
  src/css/buttons.css
  src/index.html
  tailwind.config.js
Labels: Ready to Review

#6 add image-upload button to hompage
  src/css/app.css
  src/index.html
Labels: Ready to Review

#15 Setup husky
  .eslintignore
  .eslintrc.js
  package.json
Labels: enhancement

#13 Reconfigured Webpack to include gallery.html
  package.json
  public/gallery.html
  public/index.html
  src/css/app.css
  src/css/buttons.css
  tailwind.config.js
  webpack/plugins.js
  webpack/webpack.common.js
  webpack/webpack.dev.js
  yarn.lock
Labels: Ready to Review

#12 Feature/components with tailwind "Creating Atoms"
  .eslintcache
  public/img/Man.jpg
  public/img/image.png
  public/img/imageblur.png
  public/index.html
  src/css/app.css
  src/css/buttonswithTW.css
  tailwind.config.js
  yarn.lock
Labels: Ready to Review

#17 Feature/buttons
  public/img/Vector.png
  public/img/large-anan.png
  public/img/large-avatar.png
  public/img/large-notfilled.png
  public/index.html
  src/css/buttons.css
  tailwind.config.js
Labels: Ready to Review

#22 Feature/more atoms
  package.json
  public/assets/imgs/image.png
  public/assets/imgs/poll-icon.png
  public/index.html
  src/css/banner.css
  src/css/buttons.css
  tailwind.config.js
Labels: Ready to Review

#24 Add text poll options
  public/index.html
Labels: Ready to Merge

#29 Safei/files structre
  .vscode/settings.json
  storybook/.eslintcache
  storybook/.eslintrc.js
  storybook/.gitignore
  storybook/src/App.js
  storybook/src/Safei/components/Atoms/Avatars/Avatar.stories.js
  storybook/src/Safei/components/Atoms/Avatars/anonymous.svg
  storybook/src/Safei/components/Atoms/Avatars/index.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonDisabledLG.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonDisabledMD.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonDisabledSM.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonLG.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonMD.js
  storybook/src/Safei/components/Atoms/Buttons/PrimaryButtonSM.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonDisabledLG.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonDisabledMD.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonDisabledSM.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonLG.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonMD.js
  storybook/src/Safei/components/Atoms/Buttons/SecondaryButtonSM.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/LabelInput.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/LabelInput.stories.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/StaticInput.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/StaticInput.stories.js
  storybook/src/Safei/components/Atoms/Forms/icons/ArrowDown.js
  storybook/src/Safei/components/Atoms/Forms/icons/Correct.js
  storybook/src/Safei/components/Atoms/Forms/icons/Home.js
  storybook/src/Safei/components/Atoms/Forms/icons/Wrong.js
  storybook/src/Safei/components/Atoms/Toggles/CheckBox.js
  storybook/src/Safei/components/Atoms/Toggles/CheckBox.stories.js
  storybook/src/Safei/components/Atoms/Toggles/Toggle.js
  storybook/src/Safei/components/Atoms/Toggles/Toggle.stories.js
  storybook/src/Safei/components/Atoms/Toggles/toggle.css
  storybook/src/Safei/components/MainContainer.js
  storybook/src/Safei/components/composition.js
  storybook/src/css/button.css
Labels: Ready to Review

#32 Remove appjs/add react test renderer
  storybook/.eslintcache
  storybook/.eslintrc.js
  storybook/package.json
  storybook/src/App.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/LabelInput.stories.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/LabelInput.test.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/StaticInput.stories.js
  storybook/src/Safei/components/Atoms/Forms/TextInputs/__snapshots__/LabelInput.test.js.snap
  storybook/src/Safei/components/Atoms/Toggles/CheckBox.stories.js
  storybook/src/Safei/components/Atoms/Toggles/Toggle.stories.js
  storybook/src/index.js
  storybook/yarn.lock
Labels: Ready to Review

#31 added test buttons section
  static/public/index.html
Labels: Changes Requested, Under Review

#18 added atoms for Button,Tabs,Toggle,Select and Input | added molecules for Tab Group , Privacy and Add Option
  static/public/index.html
  static/src/css/buttonswithTW.css
  yarn-error.log
  yarn.lock
Labels: Under Review

#25 Creating text options
  public/index.html
  static/public/index.html
  static/src/css/buttons.css
  storybook/.eslintcache
Labels: Ready to Review

#33 Feature/components with storybook
  storybook/.eslintcache
  storybook/.eslintcache~599fae6615bf8d84742dd6f9af46d0ffce988a75
  storybook/package.json
  storybook/src/kareem/Components/Atoms/Buttons/Button.js
  storybook/src/kareem/Components/Atoms/Buttons/Button.stories.js
  storybook/yarn.lock
Labels: Changes Requested

#26 add new organism called (text poll edit-name)
  public/index.html
  static/public/index.html
  static/src/css/buttons.css
  static/tailwind.config.js
Labels: Resolve Conflict to Approve

#45 Added atoms testing
  storybook/.eslintcache
  storybook/src/Eman/Atoms/Avatars/Avatar.test.js
  storybook/src/Eman/Atoms/Avatars/__snapshots__/Avatar.test.js.snap
  storybook/src/Eman/Atoms/Buttons/Primary-Icon-Only/BtnIconOnly.test.js
  storybook/src/Eman/Atoms/Buttons/Primary-Icon-Only/__snapshots__/BtnIconOnly.test.js.snap
  storybook/src/Eman/Atoms/Buttons/Primary-Icon/Button-icon.test.js
  storybook/src/Eman/Atoms/Buttons/Primary-Icon/__snapshots__/Button-icon.test.js.snap
  storybook/src/Eman/Atoms/Buttons/Primary/Button.test.js
  storybook/src/Eman/Atoms/Buttons/Primary/__snapshots__/Button.test.js.snap
  storybook/src/Eman/Atoms/Checkboxes/Checkbox.test.js
  storybook/src/Eman/Atoms/Checkboxes/__snapshots__/Checkbox.test.js.snap
  storybook/src/Eman/Atoms/Dividers/Divider.js
  storybook/src/Eman/Atoms/Dividers/Divider.test.js
  storybook/src/Eman/Atoms/Dividers/__snapshots__/Divider.test.js.snap
  storybook/src/Eman/Atoms/Inputs/Choices/Choices.test.js
  storybook/src/Eman/Atoms/Inputs/Choices/__snapshots__/Choices.test.js.snap
  storybook/src/Eman/Atoms/Inputs/Label/Label.test.js
  storybook/src/Eman/Atoms/Inputs/Label/__snapshots__/Label.test.js.snap
  storybook/src/Eman/Atoms/Inputs/LabelwIcon/LabelwIcon.test.js
  storybook/src/Eman/Atoms/Inputs/LabelwIcon/__snapshots__/LabelwIcon.test.js.snap
  storybook/src/Eman/Atoms/Radios/Radio.test.js
  storybook/src/Eman/Atoms/Radios/__snapshots__/Radio.test.js.snap
  storybook/src/Eman/Atoms/Toggles/Toggle.test.js
  storybook/src/Eman/Atoms/Toggles/__snapshots__/Toggle.test.js.snap
  storybook/src/Eman/Molecules/Tabs/Tab.test.js
  storybook/src/Eman/Molecules/Tabs/__snapshots__/Tab.test.js.snap
Labels: Under Review

#46 Add 2 testing libraries & add eslintcache to gitigonre
  static/.gitignore
  storybook/.gitignore
  storybook/package.json
  storybook/src/dummy.test.js
  storybook/src/setupTests.js
  storybook/yarn.lock
Labels: Ready to Review

#43 added button in storybook + commented styles
  storybook/.eslintcache
  storybook/src/Ali/Atoms/Avatar/Avatar.js
  storybook/src/Ali/Atoms/Avatar/Avatar.stories.js
  storybook/src/Ali/Atoms/TextButton/Button.js
  storybook/src/Ali/Atoms/TextButton/Button.stories.js
  storybook/src/Ali/Atoms/TextInput/TextInput.js
  storybook/src/Ali/Atoms/TextInput/TextInput.stories.js
  storybook/src/Ali/Atoms/Toggler/Toggler.js
  storybook/src/Ali/Atoms/Toggler/Toggler.stories.js
  storybook/src/Ali/Molecules/ImageUpload/ImageUpload.js
  storybook/src/Ali/Molecules/ImageUpload/ImageUpload.stories.js
  storybook/src/stories/examples/header.css
  storybook/src/stories/examples/page.css
Labels: Ready to Merge

#42 Add atoms
  .gitignore
  storybook/.eslintcache
  storybook/.gitignore
  storybook/src/Sahl/Atoms/Divider/Divider.js
  storybook/src/Sahl/Atoms/Divider/Divider.stories.js
  storybook/src/Sahl/Atoms/Divider/Divider.test.js
  storybook/src/Sahl/Atoms/Divider/__snapshots__/Divider.test.js.snap
  storybook/src/Sahl/Atoms/Input/Input.js
  storybook/src/Sahl/Atoms/Input/Input.stories.js
  storybook/src/Sahl/Atoms/Input/Input.test.js
  storybook/src/Sahl/Atoms/Input/__snapshots__/Input.test.js.snap
  storybook/src/Sahl/Atoms/Radio/Radio.js
  storybook/src/Sahl/Atoms/Radio/Radio.stories.js
  storybook/src/Sahl/Atoms/Radio/Radio.test.js
  storybook/src/Sahl/Atoms/Radio/__snapshots__/Radio.test.js.snap
  storybook/src/Sahl/Atoms/SelectDropDown/SelectDropDown.js
  storybook/src/Sahl/Atoms/SelectDropDown/SelectDropDown.stories.js
  storybook/src/Sahl/Atoms/SelectDropDown/SelectDropDown.test.js
  storybook/src/Sahl/Atoms/SelectDropDown/__snapshots__/SelectDropDown.test.js.snap
  storybook/src/Sahl/Atoms/Slider/Slider.js
  storybook/src/Sahl/Atoms/Slider/Slider.stories.js
  storybook/src/Sahl/Atoms/Slider/Slider.test.js
  storybook/src/Sahl/Atoms/Slider/__snapshots__/Slider.test.js.snap
  storybook/src/Sahl/Atoms/Toggle/Toggle.js
  storybook/src/Sahl/Atoms/Toggle/Toggle.stories.js
  storybook/src/Sahl/Atoms/Toggle/Toggle.test.js
  storybook/src/Sahl/Atoms/Toggle/__snapshots__/Toggle.test.js.snap
  storybook/src/Sahl/Molecules/Tab/Tab.js
  storybook/src/Sahl/Molecules/Tab/Tab.stories.js
  storybook/src/Sahl/Molecules/Tab/Tab.test.js
  storybook/src/Sahl/Molecules/Tab/__snapshots__/Tab.test.js.snap
  storybook/src/Sahl/assets/icons/File-outlined.js
  storybook/src/Sahl/assets/icons/Image-outlined.js
  storybook/src/Sahl/assets/icons/Poll-outlined.js
  storybook/src/Sahl/assets/icons/Stars.js
  storybook/src/Sahl/assets/icons/ThumpsDown-outlined.js
  storybook/src/Sahl/assets/icons/ThumpsDown.js
  storybook/src/Sahl/assets/icons/ThumpsUp-outlined.js
  storybook/src/Sahl/assets/icons/ThumpsUp.js
  storybook/yarn.lock
Labels: Finished Requested, Ready to Review

#34 added some atoms + molecules + organism
  static/public/index.html
Labels: In progress

#48 added molecules and organism
  storybook/src/Ali/Molecules/Privacy/Privacy.js
  storybook/src/Ali/Molecules/Privacy/Privacy.stories.js
  storybook/src/Ali/Molecules/TapGroup/PollOption/PollOption.js
  storybook/src/Ali/Molecules/TapGroup/PollOptions/PollOptions.js
  storybook/src/Ali/Molecules/TapGroup/PollOptions/PollOptions.stories.js
  storybook/src/Ali/Organismes/ImagePollDefault/ImagePollDefault.js
  storybook/src/Ali/Organismes/ImagePollDefault/ImagePollDefault.stories.js
Labels: Finished Requested, Ready to Review
